name: Release Application

on: 
  push:
    branches:
      - master
      - main

jobs:

  Build_Windows_App:
    runs-on: windows-latest

    steps:

      - name: checkout
        uses: actions/checkout@v1

      - name: Use Node.js 14.15.1
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Github Action
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Bump Version
        run: |
          npm version patch -m "v%s"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.github_token }}
          repository: 'remyar/AR_Garage'
          directory: './'

      - name: npm install
        working-directory: ${{ github.workspace }}
        run: |
          npm install

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          release: true
          github_token: ${{ secrets.github_token }}
        env:
          CI: false
          GENERATE_SOURCEMAP: false
          REACT_APP_TECDOC_API_CATALOG: ${{ secrets.REACT_APP_TECDOC_API_CATALOG }}
          REACT_APP_TECDOC_API_URL_1: ${{ secrets.REACT_APP_TECDOC_API_URL_1 }}
          REACT_APP_TECDOC_API_URL_2: ${{ secrets.REACT_APP_TECDOC_API_URL_2 }}
          REACT_APP_TECDOC_API_URL_3: ${{ secrets.REACT_APP_TECDOC_API_URL_3 }}
          REACT_APP_TECDOC_PROVIDER_ID_NEW: ${{ secrets.REACT_APP_TECDOC_PROVIDER_ID_NEW }}
          REACT_APP_TECDOC_PROVIDER_ID_OLD: ${{ secrets.REACT_APP_TECDOC_PROVIDER_ID_OLD }}
